# Standards: 2.0.0
---

# 1.1.5 Ensure noexec option set on /tmp partition

- name: 1.1.5 - Ensure noexec option set on /tmp partition
  mount:
    name: "{{ item.mount }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.options.split(',') | union(['noexec']) | join(',') }}"
  when: item.mount == '/tmp'
  with_items: "{{ ansible_mounts }}"
  tags:
    - level-1
    - section-1
    - section-1.1
    - section-1.1.5
    - "1.1.5"
    - scored
