# Standards: 2.0.0
---

# 1.7.1.4 Ensure permissions on /etc/motd are configured

- name: 1.7.1.4 - Ensure permissions on /etc/motd are configured
  file:
    path: "/etc/motd"
    owner: root
    group: root
    mode: 0644
    follow: true
  tags:
    - level-1
    - section-1
    - section-1.7
    - section-1.7.1
    - section-1.7.1.4
    - "1.7.1.4"
    - not-scored
