# Standards: 0.11
---

# 2.3.3 Ensure talk client is not installed

- name: 2.3.3 - Ensure talk client is not installed
  yum:
    name: "talk"
    state: absent
  tags:
    - level-1
    - section-2
    - section-2.3
    - "2.3.3"
    - scored
