# Standards: 2.0.0
---

# 2.3.4 Ensure telnet client is not installed

- name: 2.3.4 - Ensure telnet client is not installed
  yum:
    name: "telnet"
    state: absent
  tags:
    - level-1
    - section-2
    - section-2.3
    - section-2.3.4
    - "2.3.4"
    - scored
