# Standards: 2.0.0
---

# 5.2.11 Ensure only approved MAC algorithms are used

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.11
    - "5.2.11"
    - scored

- name: 5.2.11 - Ensure only approved MAC algorithms are used
  lineinfile:
    regexp: "^MACs\\s+"
    line: "MACs {{ cis_sshd_macs }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - section-5.2
    - section-5.2.11
    - "5.2.11"
    - scored
